force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Used to store countries name</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Used to Store type of Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/Product_Subscription__mdt.object-meta.xml
<CustomObject>
    <label>Product Subscription</label>
    <pluralLabel>Product Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Subscription__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
                <default>true</default>
                <label>Germany</label>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInfoService.cls
/*
Author: Nishant Mohan Wavhal
Apex Class to Call API Services for External partners
*/
@RestResource(urlMapping='/ProductInfoService/*')
global class ProductInfoService {   
    
    @HttpPOST
    global static void  getCustomerfeatures(String UUID) {
        
        RestRequest req = RestContext.request;
        RestResponse res =RestContext.response;
        
        String contactUUID= UUID;
        ProductMetadataWrapper mdtwrapper=null;
        Product_Subscription__mdt psubscriptioncost;
        
        String homecountry;
        String product;
        String isocode;
        
        if(contactUUID !=null && contactUUID !='')
        {  
            Contact c;
            try
            {
                c=[select id ,home_Country__c,Product__c,CurrencyIsoCode from Contact where uuid__c =:contactUUID limit 1];
            }
            catch(Exception e)
            {            
                res.responseBody=Blob.valueOf(e.getmessage());               	
            }
            
            
            if(c!=null)
            {
                if(c.home_Country__c!=null && c.product__c!=null && c.home_Country__c!='' && c.product__c!='')
                {        
                    psubscriptioncost= ProductMetaDataInfo.getproductcostconfig(c.home_Country__c,c.product__c);                     
                    homeCountry=c.home_Country__c;                  
                    product=c.product__c;                   
                    isocode=c.CurrencyIsoCode;
                }
                else
                {
                    res.responseBody=Blob.valueOf(JSON.serialize(new CustomErrorException('500','Contact Value has an Error')));
                }
            }
            
        }
        else
        {		
            
            res.ResponseBody =Blob.valueOf(JSON.serialize(new CustomErrorException('500','Please Enter Contact UUID')));
        }
        
        if(psubscriptioncost!=null)
        {           
            mdtwrapper= new ProductMetadataWrapper(homecountry,product,isocode,psubscriptioncost);
            res.statusCode=200; 
            res.ResponseBody =Blob.valueOf(JSON.serialize(mdtwrapper));
        }
        else
        {
            res.statusCode=500; 
        }
        
    } 
}