force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Used to store countries name</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Used to Store type of Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/Product_Subscription__mdt.object-meta.xml
<CustomObject>
    <label>Product Subscription</label>
    <pluralLabel>Product Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Subscription__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
                <default>true</default>
                <label>Germany</label>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInfoController.cls
/*
Author: Nishant Mohan Wavhal
Apex Class for providing Service Agents with data to view of features
while handling support case via LWC
*/

public with sharing class ProductInfoController {
    @AuraEnabled(cacheable=true)
    public static ProductMetadataWrapper getServices(Id caseId){
        
        ProductMetadataWrapper productconfigwrapper=null;     
        Product_Subscription__mdt productsubscription=null;
        
        String homecountry;
        String product;
        String isocode;
        
        if(caseId !=null)
        {
            Case cs = [select id,ContactId,contact.home_Country__c,
                        contact.CurrencyIsoCode,contact.Product__c 
                       from Case 
                       where 
                       id =:caseId WITH USER_MODE limit 1];
           
            if(cs!=null)
            { 
                if(cs.ContactId!=null)
                {

                    if(cs.contact.home_Country__c!=null  && cs.contact.product__c!=null && 
                       cs.contact.home_Country__c!='' && cs.contact.product__c!='')
                    {
                        productsubscription = 
                         CustomMetaDataInfo.getproductcostconfig(cs.contact.home_Country__c,cs.contact.product__c);                     
                        homeCountry=cs.contact.home_Country__c;
                        product=cs.contact.product__c;
                        isocode=cs.contact.CurrencyIsoCode;
                        
                        if(productsubscription!=null)
                        {
                         productconfigwrapper= 
                          new ProductMetadataWrapper(homecountry,product,isocode,productsubscription);
                        } 
                    }
                    else
                        throw new AuraHandledException('Contact has Product / Home Country missing'); 
                }
                else
                    throw new AuraHandledException('Contact Value is Null'); 
            }
            
        }
       
        return productconfigwrapper;         
    } 
}