force-app/main/default/objects/Product_Subscription__mdt/Product_Subscription__mdt.object-meta.xml
<CustomObject>
    <label>Product Subscription</label>
    <pluralLabel>Product Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Subscription__mdt/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>%ATM Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
                <default>true</default>
                <label>Germany</label>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/fields/Monthly_Charges__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Charges__c</fullName>
    <label>Monthly Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Subscription__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomMetaDataInfo.cls
/*
Author: Nishant Mohan Wavhal
Apex Class CustomMetaDataInfo for retrieving metadata info for 
as single responsibilty various custom metatdata
*/

public class CustomMetaDataInfo {
        
    public static Product_Subscription__mdt getproductcostconfig(String homecountry,String product)
    { 
        return [select id,atm_fee__c,Card_Replacement_Cost__c,Monthly_Charges__c from Product_Subscription__mdt where home_Country__c=:homecountry and product__c=:Product limit 1 ];
        
    }
    
}